services:
  dashboard:
    container_name: himalayan-drumming-dashboard
    build:
      dockerfile: ./docker/Dockerfile
      context: .
    env_file:
      - .env
    volumes:
      - ./blob:/app/blob:rw
    ports:
      - 8080:80
  database:
    image: postgres:17-alpine
    container_name: himalayan-drumming-database
    env_file:
      - .env
    expose:
      - "5432"
