# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/refs/heads/main/schema/compose-spec.json
services:
  frontend:
    image: ghcr.io/scott181182/himalayan-drumming:${TAG:-latest}
    container_name: himalayan-drumming-frontend
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env.local
    volumes:
      - ./blob:/blob:rw
    ports:
      - 3100:3000
    pre_start:
      - image: ghcr.io/scott181182/himalayan-drumming/db-migrate:${TAG:-latest}

  database:
    image: postgres:17-alpine
    container_name: himalayan-drumming-database
    env_file:
      - .env
    expose:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data:rw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      start_period: 30s
      timeout: 10s
      interval: 10s
      retries: 5
volumes:
  pgdata:
