# This file is mostly to define the build contexts for each Docker image in this repository
services:
  frontend:
    image: ghcr.io/scott181182/himalayan-drumming/frontend:${TAG:-latest}
    container_name: himalayan-drumming-frontend
    build:
      context: .
      target: frontend
    env_file:
      - .env
    environment:
      - SSR_API_HOST=http://backend:3001
    ports:
      - 3100:3000
  backend:
    image: ghcr.io/scott181182/himalayan-drumming/backend:${TAG:-latest}
    container_name: himalayan-drumming-backend
    build:
      context: .
      target: backend
    env_file:
      - .env
    environment:
      - BLOB_ROOT=/data/blob
    volumes:
      - ./blob:/data/blob:rw
    ports:
      - 3101:3001
  database:
    image: postgres:17-alpine
    container_name: himalayan-drumming-database
    env_file:
      - .env
    ports:
      - 5433:5432
