#import VillageInContext from "./context.graphql"

fragment SimpleVillage on Village {
  id
  name

  location {
    id
    latitude
    longitude
  }
}

query GetVillage($villageId: ID!) {
  village(where: { id: $villageId }) {
    ...VillageInContext
  }
}
query GetAllVillages {
  villages {
    ...SimpleVillage
  }
}

mutation CreateVillage($data: VillageCreateInput!) {
  createVillage(data: $data) {
    ...SimpleVillage
  }
}

mutation UpdateVillage($villageId: ID!, $data: VillageUpdateInput!) {
  updateVillage(where: { id: $villageId }, data: $data) {
    ...VillageInContext
  }
}

mutation RemovePersonFromVillage($villageId: ID!, $personId: ID!) {
  deletePersonInVillage(
    where: { personId_villageId: { personId: $personId, villageId: $villageId } }
  ) {
    personId
    villageId
  }
}
