version: '3.7'
services:
  workspace:
    container_name: ${APP_NAME}-workspace
    build:
      dockerfile: ./.devcontainer/Dockerfile
      context: ..
    env_file:
      - .env
    volumes:
      - ..:/workspace:rw
      - ${HOME}/.ssh:/home/node/.ssh:ro
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf:ro
      - ./nginx/default.conf:/etc/nginx/sites-available/default:ro
    ports:
      - 8080:80
      - 3001:3001
    tty: true
    command: bash
