name: himalayan-drumming-dev
services:
  workspace:
    container_name: himalayan-drumming-dev-workspace
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    volumes:
      - ..:/workspace:rw
      - ${HOME}/.ssh:/home/node/.ssh:ro
    ports:
      - 3000:3000
      - 3001:3001
    tty: true
    command: zsh
  database:
    image: postgres:17-alpine
    container_name: himalayan-drumming-dev-database
    env_file:
      - .env
    ports:
      - 5432:5432
