# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Check

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  check:
    name: Lint, Type Check, and Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env:
      BLOB_ROOT: ${{ vars.BLOB_ROOT }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Node, PNPM, and Dependencies
        uses: pnpm/setup@v2
        with:
          runtime: node@${{ matrix.node-version }}
          cache: true
          install: true
      - name: Generate
        run: pnpm generate && pnpm next typegen
      - name: Lint
        run: pnpm lint
      - name: Type Check
        run: pnpm typecheck
      - name: Build
        run: pnpm build
