name: Publish

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    name: Build and Publish Docker Images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Frontend Metadata
        id: meta_frontend
        uses: docker/metadata-action@v5
        with:
          tags: |
            type=semver,pattern={{version}}
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/frontend
          bake-target: frontend
      - name: Extract Backend Metadata
        id: meta_backend
        uses: docker/metadata-action@v5
        with:
          tags: |
            type=semver,pattern={{version}}
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/backend
          bake-target: backend

      - name: Build and Push Docker Images
        id: publish
        uses: docker/bake-action@v6
        with:
          files: |
            ./compose.yml
            cwd://${{ steps.meta_frontend.outputs.bake-file }}
            cwd://${{ steps.meta_backend.outputs.bake-file }}
          targets: frontend,backend
          push: true
